# -*- coding: utf-8 -*-
"""Connection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzO92eD6xtTTvwPUfDLejtB2yseTE27y
"""

!pip install pyngrok==4.1.1
!pip install flask-ngrok
!ngrok authtoken '2aa1SKJc6y9ZeSxUozSFGxHIFkb_5frrrUG7DXmkV9hTeqP2L'

from google.colab import drive
drive.mount('/content/drive')

import sqlite3
db_folder='/content/drive/MyDrive/4Owlz'
conn=sqlite3.connect(db_folder+'mydatabase.db')
cursor = conn.cursor()
#query
create_table_query ='''
CREATE TABLE IF NOT EXISTS users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS profile(
  username TEXT NOT NULL,
  role TEXT Not NULL,
  address TEXT NOT NULL,
  intro TEXT NOT NULL,
  contact TEXT NOT NULL,
  email TEXT NOT NULL,
  linked TEXT NOT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
)
'''
cursor.execute(create_table_query)

create_table_query='''
CREATE TABLE IF NOT EXISTS description(
  username TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS education(
  course TEXT NOT NULL,
  school TEXT NOT NULL,
  date TEXT NOT NULL
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS language(
  language TEXT NOT NULL
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS skill(
  username TEXT NOT NULL,
  skills TEXT NOT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS hobby(
  username TEXT NOT NULL,
  hobby TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
)
'''
cursor.execute(create_table_query)


create_table_query ='''
CREATE TABLE IF NOT EXISTS project(
  system TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT NOT NULL
)
'''
cursor.execute(create_table_query)

create_table_query ='''
CREATE TABLE IF NOT EXISTS contact(
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  source TEXT NOT NULL,
  type TEXT NOT NULL,
  budget TEXT NOT NULL,
  detail TEXT NOT NULL
)
'''
cursor.execute(create_table_query)
conn.commit()

import sqlite3
db_folder='/content/drive/MyDrive/4Owlz'
conn=sqlite3.connect(db_folder+'mydatabase.db')
cursor = conn.cursor()
#List of user data
insert_query = '''
INSERT INTO users (username) VALUES (?)
'''
users = ["Tracy Liaw Mien Yee", "Chong Kar Min", "Low Wei Jie", "Derrick Saw Wei Heng"]
for user in users:
  cursor.execute(insert_query, (user,))
  conn.commit()

# List of profile data
insert_query = '''
INSERT INTO profile (username, role, address, intro, contact, email, linked) VALUES (?,?, ?, ?, ?, ?,?)
'''
profiles = [
    ("Tracy Liaw Mien Yee", "Frontend Developer", "Kuching, Sarawak", "Hey there! I'm Tracy Liaw, a dedicated Computer Science student with a passion for crafting engaging user experiences. My journey in tech is fueled by a keen interest in UI/UX design and front-end development. I find joy in the details that make software not just functional, but also intuitive and delightful to use.","109799677","yliawt02@gmail.com","in/liawyee"),
    ("Chong Kar Min", "Project Analyst", "Chemor, Perak", "Hello! I'm Chong Kar Min, a devoted student of Computer Science with a deep-seated interest in the world of project analytics. My path in the technology sector is driven by a fascination with data analysis and its impact on software development processes. I revel in unraveling complex data sets to derive meaningful insights that not only enhance software functionality but also optimize performance.", "125658452", "karminchong88@gmail.com","in/karmin-chong-3b7b772a7"),
    ("Low Wei Jie", "Database Manager", "Kepong, Kuala Lumpur", "Hey there! I'm Low Wei Jie, a committed Computer Science student deeply engrossed in the world of database management and backend development. My technological journey is propelled by a profound interest in data structures, efficient database solutions, and backend architecture. I revel in the challenge of organizing and managing data, ensuring it's not only secure but also easily accessible and performant.", "102440951","weijie0429@gmail.com","in/low-weijie-3154ba2a8"),
    ("Derrick Saw Wei Heng", "Security Manager", "Buterworth, Penang", "Hey there! I'm Derrick Saw, a committed Computer Science student with a deep interest in ensuring the security and integrity of software systems. My journey in technology is driven by my fascination with cybersecurity and network security. I take pride in understanding the complexities that underpin secure systems, making them not only robust but also trustworthy and reliable.", "174309025", "derricksaw123@gmail.com", "in/saw-derrick-3a7b3b258/")
]
for record in profiles:
    cursor.execute(insert_query, record)
    conn.commit()

#List of description data
insert_query = '''
INSERT INTO description (username, description) VALUES (?,?)
'''
description = [
    ("Tracy Liaw Mien Yee","Hey there! I'm Tracy Liaw, a dedicated Computer Science student with a passion for crafting engaging user experiences. My journey in tech is fueled by a keen interest in UI/UX design and front-end development. I find joy in the details that make software not just functional, but also intuitive and delightful to use."),
    ("Tracy Liaw Mien Yee","As I look toward the future, my sights are set on becoming a front-end developer where I can merge technical prowess with creative design. I'm eager to continue exploring the ever-evolving landscape of user interface design, pushing the boundaries of what's possible, and leaving my mark on the next generation of digital experiences."),
    ("Tracy Liaw Mien Yee","Whether it's through collaborative projects, internships, or personal ventures, I'm on a mission to deepen my understanding of the front-end realm and contribute to meaningful projects that resonate with users. Watch this space — I'm just getting started!"),
    ("Chong Kar Min", "Hello! I'm Chong Kar Min, a devoted student of Computer Science with a deep-seated interest in the world of project analytics. My path in the technology sector is driven by a fascination with data analysis and its impact on software development processes. I revel in unraveling complex data sets to derive meaningful insights that not only enhance software functionality but also optimize performance."),
    ("Chong Kar Min", "Looking forward, my goal is to excel as a Project Analyst, blending analytical skills with strategic planning. I am committed to diving deeper into the realms of data analytics and project management, navigating the dynamic field of software development."),
    ("Chong Kar Min", "Through team collaborations, internships, and personal endeavors, I am determined to enrich my expertise in analytics and contribute significantly to projects that not only meet but exceed user expectations. This is just the beginning of my journey in shaping efficient and impactful software solutions. Stay tuned for what's next!"),
    ("Low Wei Jie","Hey there! I'm Low Wei Jie, a committed Computer Science student deeply engrossed in the world of database management and backend development. My technological journey is propelled by a profound interest in data structures, efficient database solutions, and backend architecture. I revel in the challenge of organizing and managing data, ensuring it's not only secure but also easily accessible and performant."),
    ("Low Wei Jie","As I gaze into the future, my ambition is to evolve into a seasoned database manager, where I can blend my analytical skills with innovative database strategies. I am enthusiastic about delving further into the dynamic field of database technology, breaking new ground in data handling, and contributing to the development of robust and scalable systems."),
    ("Low Wei Jie", "Through team projects, internships, or my own initiatives, I am dedicated to enhancing my expertise in database management and playing a pivotal role in projects that leave a lasting impact. Keep an eye on this space — my journey in the realm of databases is just beginning!"),
    ("Derrick Saw Wei Heng","Hey there! I'm Derrick Saw, a committed Computer Science student with a deep interest in ensuring the security and integrity of software systems. My journey in technology is driven by my fascination with cybersecurity and network security. I take pride in understanding the complexities that underpin secure systems, making them not only robust but also trustworthy and reliable."),
    ("Derrick Saw Wei Heng","Looking ahead, my goal is to become a security manager, blending my technical knowledge with strategic planning. I am enthusiastic about delving into the dynamic field of cybersecurity, tackling challenges that safeguard digital information, and setting new standards in data protection."),
    ("Derrick Saw Wei Heng","Through collaborative projects, internships, or individual initiatives, I am dedicated to enhancing my expertise in security management. I aim to contribute to projects that demand high security, ensuring user safety and data integrity. Keep an eye on this space — I am on my way to making a significant impact in the world of software security!")
]
for describe in description:
  cursor.execute(insert_query, describe)
  conn.commit()

# List of education data
insert_query = '''
INSERT INTO education (course, school, date) VALUES (?, ?, ?)
'''
educations = [
    ("Bachelor of Computer Science", "Universiti Utara Malaysia (UUM)", "OCT2021-MAY2025")
]
for education in educations:
    cursor.execute(insert_query, education)
    conn.commit()

# List of language data
insert_query = '''
INSERT INTO language (language) VALUES ( ?)
'''
languages = [
    ("HTML5"),
    ("CSS3"),
    ("JavaScript"),
    ("Python"),
    ("Java")

]
for language in languages:
    cursor.execute(insert_query, (language,))
    conn.commit()

# List of skills data
insert_query = '''
INSERT INTO skill (username, skills) VALUES (?, ?)
'''
skills = [
    ("Tracy Liaw Mien Yee","Website and Mobile Development"),
    ("Tracy Liaw Mien Yee","Responsive Design"),
    ("Tracy Liaw Mien Yee","UI / UX"),
    ("Tracy Liaw Mien Yee","Performance Optimization"),
    ("Tracy Liaw Mien Yee","Software Testing"),
    ("Chong Kar Min","Data Analysis"),
    ("Chong Kar Min","Data Visualization"),
    ("Chong Kar Min","Statistics"),
    ("Chong Kar Min","Machine Learning"),
    ("Chong Kar Min","Reporting and Communication"),
    ("Low Wei Jie","Database Design"),
    ("Low Wei Jie","Query Optimizer"),
    ("Low Wei Jie","Backup and Recovery"),
    ("Low Wei Jie","Monitoring"),
    ("Low Wei Jie","Troubleshooting"),
    ("Derrick Saw Wei Heng","Risk Assessment and Management"),
    ("Derrick Saw Wei Heng","Network and System Security"),
    ("Derrick Saw Wei Heng","Application Security"),
    ("Derrick Saw Wei Heng","Data Protection"),
    ("Derrick Saw Wei Heng","Cloud Security")
]
for skill in skills:
    cursor.execute(insert_query, skill)
    conn.commit()

#List of hobby data
insert_query = '''
INSERT INTO hobby (username,hobby, description) VALUES (?,?,?)
'''
hobbies = [
    ("Tracy Liaw Mien Yee","Crochet","Crochet is a therapeutic and calming hobby favored by those who find solace in crafting intricate and textured patterns, suitable for a wide array of projects, including wearables and accessories. It offers a means of spending time in a way that allows for the creation of one's desires."),
    ("Chong Kar Min","Drawing","Drawing brings joy and fulfillment to those who engage in it, allowing them to express themselves and explore their creativity. It provides moments of happiness as they bring their ideas to life through lines, shapes, and colors on paper or canvas."),
    ("Low Wei Jie","Swimming","I love swimming because it provides a perfect escape from the daily grind. The sensation of gliding through the water, the gentle sound of my own breath, and the feel of the water supporting me create a serene and peaceful environment. So, for me, swimming is not just a hobby; it's a blissful retreat that rejuvenates my body and soul."),
    ("Derrick Saw Wei Heng","Music", "Music is my hobby, a simple yet fulfilling pastime. I enjoy immersing myself in diverse genres, letting rhythms and melodies enhance my mood. Whether for an energy boost or relaxation, music adds depth to daily experiences. Exploring new genres and appreciating diverse artistry, it complements various activities, providing a soundtrack to different moments in my life.")
]
for hobby in hobbies:
  cursor.execute(insert_query, hobby)
  conn.commit()

#List of project data
insert_query = '''
INSERT INTO project (date,system, description) VALUES (?,?,?)
'''
projects = [
    ("DEC2022-JAN2023", "Quoffe Coffee Membership System","This system enables users to manage their member accounts online. This system allows online redemption and ordering for their favourite coffee via any device on their hands. Pickup or cofee delivery is easily achieved by using our website. We will also provide an online management of the VIP member accounts if thery wish to sign up as a new VIP member or log into their existing accounts."),
    ("OCT2023-DEC2023","TechKids Forum Website","This system allows user to take part in a forum which topics on the kids attachment towards gadgets. Users are free to create and log into their account to participate in any existing forums or even create their own forum topics. The tags are also available to allow users to search for their desired content."),
]
for project in projects:
  cursor.execute(insert_query, project)
  conn.commit()

from flask import Flask, render_template, request, redirect
from flask.templating import render_template
from flask_ngrok import run_with_ngrok
import sqlite3, secrets
templates_folder='/content/drive/MyDrive/4Owlz/templates'
static_folder = '/content/drive/MyDrive/4Owlz/assets'
app = Flask(__name__, template_folder=templates_folder, static_folder=static_folder)
run_with_ngrok(app)

db_folder='/content/drive/MyDrive/4Owlz'


app.secret_key = secrets.token_hex(32)

@app.route("/")
def landing():
  return render_template("land.html")

@app.route("/home")
def home():
  conn=sqlite3.connect(db_folder+'mydatabase.db')
  cursor = conn.cursor()
  query = 'SELECT * FROM profile'
  cursor.execute(query)
  profiles = cursor.fetchall()
  query = 'SELECT * FROM skill'
  cursor.execute(query)
  skills = cursor.fetchall()
  return render_template("index.html", profiles=profiles, skills=skills)

@app.route("/hobby")
def hobby():
  name = request.args.get('name', default=None)
  conn=sqlite3.connect(db_folder+'mydatabase.db')
  cursor = conn.cursor()
  query = 'SELECT * FROM hobby WHERE username = ?'
  cursor.execute(query,(name,))
  hobby = cursor.fetchone()
  return render_template("hobby.html", hobby=hobby)

@app.route("/portfolio")
def portfolio():
  name = request.args.get('name', default=None)
  conn=sqlite3.connect(db_folder+'mydatabase.db')
  cursor = conn.cursor()
  query = 'SELECT * FROM profile where username=?'
  cursor.execute(query,(name,))
  profile = cursor.fetchone()
  query = 'SELECT * FROM education'
  cursor.execute(query)
  education = cursor.fetchone()
  query = 'SELECT * FROM project'
  cursor.execute(query)
  project = cursor.fetchall()
  query = 'SELECT * FROM language'
  cursor.execute(query)
  language = cursor.fetchall()
  query = 'SELECT description FROM description WHERE username=?'
  cursor.execute(query,(name,))
  description = cursor.fetchall()
  query = 'SELECT hobby FROM hobby WHERE username=?'
  cursor.execute(query,(name,))
  hobby = cursor.fetchone()
  return render_template("portfolio.html",profile=profile,education=education, project=project, language=language, description=description, hobby=hobby)

@app.route("/contact")
def contact():
  return render_template("contact.html")

@app.route("/service",methods=["POST"])
def service():
  name=request.form.get('name')
  email=request.form.get('email')
  source=request.form['source']
  project_type=request.form['type']
  budget=request.form['budget']
  detail=request.form.get('details')
  conn=sqlite3.connect(db_folder+'mydatabase.db')
  cursor = conn.cursor()
  insert_query='INSERT INTO contact(name,email,source,type,budget,detail) VALUES(?,?,?,?,?,?)'
  cursor.execute(insert_query,(name,email,source,project_type,budget,detail))
  conn.commit()
   # Set a flag to indicate successful submission
  submission_successful = True
  print(submission_successful)
  return render_template("contact.html", submission_successful=submission_successful)

@app.route("/project")
def project():
  conn=sqlite3.connect(db_folder+'mydatabase.db')
  cursor = conn.cursor()
  query = 'SELECT * FROM project'
  cursor.execute(query)
  project = cursor.fetchall()
  return render_template("project.html", project=project)

@app.route("/faq")
def faq():
  return render_template("faq.html")

app.run()

conn=sqlite3.connect(db_folder+'mydatabase.db')
cursor = conn.cursor()

#Retrieve the data from service table
query='SELECT * FROM contact'
cursor.execute(query)
services = cursor.fetchall()

print("Project Request:")
for service in services:
  print("-----------------------")
  print("Username: " + service[0])
  print("Email: " + service[1])
  print("Source: " + service[2])
  print("Project Type: " + service[3])
  print("Project Budget: " + service[4])
  print("Project Details: " + service[5])
  print("-----------------------")
  print("")